### ISSUE TITLE
Deployment is broken

### ISSUE THREAD

**Issue by gr2m** [neighbourhoodie/voice-of-interconnect#20]
Problem with webpack that I just added to the project:
https://travis-ci.org/neighbourhoodie/voice-of-interconnect#L1173

Looking into it

**Comment by gr2m** [comment]
I got the problem fixed via #21. But the deployment does not seem to include the `dist/` folder from which hoodie serves its static assets. Currently the default hoodie UI is shown at https://voice-of-interconnect-staging.mybluemix.net/ (It says `public/` folder but that’s hardcoded, hoodie is set to serve from `dist/`)

Is it possible that the problem is that we ignore `dist/` in gitignore? It's not listed in `.cfignore`

Any idea @markwatsonatx?

**Comment by markwatsonatx** [comment]
Fixed in pull request #26. webpack running in postinstall script now.
