### ISSUE TITLE
Bluemix deploy: do not run `npm run build` on Bluemix

### ISSUE THREAD

**Issue by gr2m** [neighbourhoodie/voice-of-interconnect#44]
We run `npm run build` on travis. The deployment to Bluemix should include an upload of the `dist/` folder, so we shouldn’t need to run the build task again on bluemix.

We should then be able to remove the `postinstall` hook from the package.json:
https://github.com/neighbourhoodie/voice-of-interconnect/blob/01e0c24e9daa95abebb921be1f9f2b971c1d8314/package.json#L9

**Comment by gr2m** [comment]
We should then also be able to move dependencies that we only need to build `dist/` into `devDependencies`. The only dependencies we need in production are

- fluent-ffmpeg
- hoodie
- watson-developer-cloud

**Comment by gr2m** [comment]
add `skip_cleanup: true` to `.travis.yml` so that the  `dist/` folder does not get removed before we deploy

**Comment by markwatsonatx** [comment]
Fixed in PR #45
