### ISSUE TITLE
reset recording view after closing list view

### ISSUE THREAD

**Issue by gr2m** [neighbourhoodie/voice-of-interconnect#51]
![kapture 2017-03-06 at 22 15 39](https://cloud.githubusercontent.com/assets/39992/23644095/5058116e-02ba-11e7-8f23-95ba4f89f92f.gif)

Also after finishing recording the canvas is fully filled with the color of the audiowaves, which is a bug I guess?

**Comment by kidfribble** [comment]
This has been fixed
