### ISSUE TITLE
App: add web app manifest for installation on home screen

### ISSUE THREAD

**Issue by gr2m** [neighbourhoodie/voice-of-interconnect#75]
see https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/ for options

**Comment by gr2m** [comment]
I’ve prepared things in https://github.com/neighbourhoodie/voice-of-interconnect/pull/77. You can play around with the colors and it would be nice to have an icon for the app

**Comment by kidfribble** [comment]
Closed with https://github.com/neighbourhoodie/voice-of-interconnect/pull/108
