### ISSUE TITLE
Make it work in Safari

### ISSUE THREAD

**Issue by gr2m** [neighbourhoodie/voice-of-interconnect#83]
- [x] support websql for PouchDB (https://github.com/neighbourhoodie/voice-of-interconnect/pull/85)
- [x] show error message when trying to record a voice memo, ask to enter a text message instead.

It currently shows no butons

<img width="362" alt="image" src="https://cloud.githubusercontent.com/assets/39992/23972712/103c3df8-0990-11e7-9c75-fd20ed8370e0.png">

**Comment by gr2m** [comment]
let’s add PostCSS and see if it fixes it

**Comment by kidfribble** [comment]
@gr2m has already fixed this by adding a left value, and in an open PR now is a style for tech errors for #97
