### ISSUE TITLE
Create tech specific warnings

### ISSUE THREAD

**Issue by kidfribble** [neighbourhoodie/voice-of-interconnect#87]
Create a way to communicate to users that their device does not allow for certain tech. Perhaps just a blanket statement saying "Best on Android Chrome v56"

Related issue: https://github.com/neighbourhoodie/voice-of-interconnect/issues/47

**Comment by kidfribble** [comment]
We need to sniff out Android Chrome versions and detect iOS

**Comment by gr2m** [comment]
@kidfribble Instead of sniffing browsers, I checked for support of audio recording directly, will start a PR in a minute
